/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author NILDA
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opcion1 = new javax.swing.JMenu();
        ItemNueva = new javax.swing.JMenuItem();
        ItemVer = new javax.swing.JMenuItem();
        Opcion2 = new javax.swing.JMenu();
        ItemCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1033, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        Opcion1.setBackground(new java.awt.Color(0, 102, 102));
        Opcion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));
        Opcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/invoice_78456.png"))); // NOI18N
        Opcion1.setText("FACTURAS");
        Opcion1.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N

        ItemNueva.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        ItemNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder-print-4341315_120555.png"))); // NOI18N
        ItemNueva.setText("Nueva");
        ItemNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNuevaActionPerformed(evt);
            }
        });
        Opcion1.add(ItemNueva);

        ItemVer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        ItemVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/system_finder_21376 (1).png"))); // NOI18N
        ItemVer.setText("Ver");
        ItemVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemVerActionPerformed(evt);
            }
        });
        Opcion1.add(ItemVer);

        jMenuBar1.add(Opcion1);

        Opcion2.setBackground(new java.awt.Color(0, 102, 102));
        Opcion2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));
        Opcion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings_gear_cog_icon_177000.png"))); // NOI18N
        Opcion2.setText("CONFIGURACIONES");
        Opcion2.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N

        ItemCerrar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        ItemCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/power_on_off_icon_153694.png"))); // NOI18N
        ItemCerrar.setText("Cerrar sesión");
        ItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCerrarActionPerformed(evt);
            }
        });
        Opcion2.add(ItemCerrar);

        jMenuBar1.add(Opcion2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNuevaActionPerformed
        // TODO add your handling code here:
        FrmNueva MiNueva = new FrmNueva();
        MiNueva.setVisible(true);
        MiNueva.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ItemNuevaActionPerformed

    private void ItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCerrarActionPerformed
        // TODO add your handling code here:
        FrmInicioSesion MiInicio = new FrmInicioSesion();
        MiInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItemCerrarActionPerformed

    private void ItemVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemVerActionPerformed
        // TODO add your handling code here:
        FrmVer MiVer = new FrmVer();
        MiVer.setVisible(true);
        MiVer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ItemVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCerrar;
    private javax.swing.JMenuItem ItemNueva;
    private javax.swing.JMenuItem ItemVer;
    private javax.swing.JMenu Opcion1;
    private javax.swing.JMenu Opcion2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
